FROM mambaorg/micromamba:0.25.1
LABEL version="2.0.0" \
      maintainer="prjemian <prjemian@gmail.com>" \
      lastupdate="2022-09-25"

# HINTS
#   docker build --tag my_iocs .
#   docker run -it --rm my_iocs bash

COPY --chown=$MAMBA_USER:$MAMBA_USER env.yml /tmp/env.yml

RUN micromamba install -y -n base -f /tmp/env.yml && \
    micromamba clean --all --yes

ARG MAMBA_DOCKERFILE_ACTIVATE=1  # (otherwise python will not be found)
ENV EDITOR="nano"

# example python command:
# RUN python -c 'import uuid; print(uuid.uuid4())' > /tmp/my_uuid
USER  $MAMBA_USER

# FIXME: cannot run as root
# E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
RUN echo "# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start OS update"
# RUN \
#     DEBIAN_FRONTEND=noninteractive apt-get update  -y && \
#     DEBIAN_FRONTEND=noninteractive apt-get install -y  \
#        libnet-dev \
#        libpcap-dev \
#        libusb-1.0-0-dev \
#        libusb-dev \
#        libx11-dev \
#        libxext-dev \
#        && \
#     rm -rf /var/lib/apt/lists/*
RUN echo "# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end OS update"

RUN echo "# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start synApps prep"
# from epics-base package:
# EPICS_BASE=/opt/conda/epics
# EPICS_BASE_HOST_BIN=/opt/conda/epics/bin/linux-x86_64
# EPICS_BASE_VERSION=7.0.6.1
# EPICS_HOST_ARCH=linux-x86_64

# additional software packages added here
ENV APP_ROOT=/home/$MAMBA_USER
# RUN mkdir -p $APP_ROOT/synApps && cd $APP_ROOT/synApps

# ENV MOTOR_HASH=master
ENV CAPUTRECORDER_HASH=master
ENV MOTOR_HASH=R7-2-2
ENV SYNAPPS="${APP_ROOT}/synApps"
ENV SUPPORT="${SYNAPPS}/support"
ENV PATH="${PATH}:${SUPPORT}/utils"
# ENV AD=${SUPPORT}/areaDetector-master
ENV MOTOR=${SUPPORT}/motor-${MOTOR_HASH}
ENV XXX=${SUPPORT}/xxx-R6-2
ENV IOCXXX=${XXX}/iocBoot/iocxxx
RUN echo "# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end synApps prep"

RUN echo "# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start assemble_synApps.sh"
WORKDIR ${APP_ROOT}
RUN pwd && ls -lAFgh
# download the installer script
# ENV HASH=master
# ENV HASH=R6-2
ENV HASH=R6-2-1
ADD --chown=$MAMBA_USER:$MAMBA_USER https://raw.githubusercontent.com/EPICS-synApps/support/${HASH}/assemble_synApps.sh ./
# edit the script first!
COPY --chown=$MAMBA_USER:$MAMBA_USER ./ioc_files/*  ./
RUN bash ./edit_assemble_synApps.sh 2>&1 | tee edit_assemble.log
# done editing
# review
# RUN cat ./assemble_synApps.sh
# run the script now
RUN bash ./assemble_synApps.sh 2>&1 | tee assemble.log

WORKDIR ${SUPPORT}
RUN pwd && ls -lAFgh
RUN echo "# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end assemble_synApps.sh"


RUN echo "# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start build synApps"
WORKDIR ${SUPPORT}
RUN pwd && ls -lAFgh
RUN make -j4 release rebuild 2>&1 | tee build.log
RUN echo "# --- Building XXX IOC ---" 2>&1 | tee -a build.log
RUN make -C ${IOCXXX}/ 2>&1 | tee -a build.log
RUN ln -s ${IOCXXX}/ ./iocxxx
# RUN ln -s ${IOCXXX}/ /home/$MAMBA_USER/iocxxx
RUN echo "# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end build synApps"

RUN echo "# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start copy screens"
# # copy all the MEDM/CSSBOY/caQtDM/... screens to /home/$MAMBA_USER/screens
# COPY --chown=$MAMBA_USER:$MAMBA_USER ioc_files/copy_screens.sh /home/$MAMBA_USER
# RUN bash /home/$MAMBA_USER/copy_screens.sh ${SUPPORT} /home/$MAMBA_USER/screens | tee -a /home/$MAMBA_USER/copy_screens.log
# # use this script in all IOCs
# COPY --chown=$MAMBA_USER:$MAMBA_USER ioc_files/modify_adl_in_ui_files.sh /home/$MAMBA_USER
# RUN bash /home/$MAMBA_USER/modify_adl_in_ui_files.sh  /home/$MAMBA_USER/screens/ui
RUN echo "# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end copy screens"

# -------
WORKDIR /home/$MAMBA_USER
